steps:
  mtaBuild:
        mtaJarLocation: /opt/sap/mta
  neoDeploy:
        neoHome: /opt/sap/neo
        host: hanatrial.ondemand.com
        account: d025390trial
        neoCredentialsId: neoDeploy
